name: Docker Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
env:
  REPOSITORY: strongswan
  PACKAGE_REGISTRY: ghcr.io

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run hadolint
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
          ignore: "DL3008"

  build:
    name: Build Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and cache
        uses: docker/build-push-action@v3
        with:
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
            linux/mips64le
            linux/ppc64le
            linux/s390x
          cache-to: type=gha, mode=max
          cache-from: type=gha
          outputs: type=cacheonly
